export {default as HomePage} from './HomePage/HomePage'
export {default as LoginPage} from './AuthPage/LoginPage'
export {default as RegisterPage} from './AuthPage/RegisterPage'
// export {default as HomePage} from './'
// export {default as HomePage} from './HomePage/HomePage'
// export {default as HomePage} from './HomePage/HomePage'
